Repository SarthakKeshari/calc_for_everything, pull requests merged in 2023-10, with the labels that each got.

#17 added compound interest calculator
  calculators/src/mathematical/compound_interest/MainCI.js
Labels: hacktoberfest2023, 🎉ranked, hacktoberfest-accepted

#16 Added BIN to hexadecimal calculater and vice versa
  calculators/src/computer_science/HexToBinAndBinToHex/MainHexToBinAndBinToHex.js
Labels: hacktoberfest2023, 🎉ranked, hacktoberfest-accepted

#19 Added Copy To Clipboard (Feature)
  calculators/package-lock.json
  calculators/package.json
  calculators/src/components/CopyValue.jsx
  calculators/src/computer_science/BinaryAdder/MainBinaryAdder.js
  calculators/src/computer_science/HexToBinAndBinToHex/MainHexToBinAndBinToHex.js
  calculators/src/computer_science/OctToBinAndBinToOct/MainOctToBinAndBinToOct.js
  calculators/src/computer_science/OctalAdder/MainOctalAdder.js
  calculators/src/index.css
  calculators/src/mathematical/compound_interest/MainCI.js
  calculators/src/mathematical/simple_interest/MainSI.js
Labels: hacktoberfest2023, 🎉ranked, hacktoberfest-accepted

#14 added hexadecimal adder
  calculators/src/computer_science/HexadecimalAdder/MainHexadecimalAdder.js
Labels: hacktoberfest2023, hacktoberfest-accepted

#21 Statistics calculator
  calculators/src/mathematical/statistics/MainStatistics.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#27 completed requirements
  calculators/src/mathematical/prime_factors/MainPrimeFactors.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#35 Added Quadratic Equation Solver
  calculators/src/mathematical/quadratic_equation_solver/MainQuadraticEquationSolver.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#43 Log and Antilog Calculator
  calculators/src/mathematical/log_antilog/MainLogAntilog.js
  calculators/src/mathematical/log_antilog/mainLogAntilog.css
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#44 Linear Equations intersection Calculator
  calculators/src/mathematical/linear_eq_intersection/MainLinearEquationIntersection.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#48 Calculator for set operations
  calculators/src/mathematical/set_operations/MainSetOperations.js
  calculators/src/mathematical/set_operations/index.css
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#51 BMR calculator
  calculators/src/health/BMR/Bmr.css
  calculators/src/health/BMR/MainBMR.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#57 Added Binary Subraction
  calculators/src/App.js
  calculators/src/Home.js
  calculators/src/computer_science/BinarySubstractor/MainBinarySubstractor.js
  calculators/src/computer_science/BinarySubtractor/MainBinarySubtractor.js
Labels: easy, hacktoberfest2023, 🎉ranked, hacktoberfest-accepted

#60 #36 Matrix Addition
  calculators/src/mathematical/matrix_addition/MainMatrixAddition.js
  calculators/src/mathematical/matrix_substraction/MainMatrixSubstraction.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#65 Determinant of Matrix
  calculators/src/mathematical/matrix_determinant/MainMatrixDeterminant.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#69 number_type_finder
  calculators/src/computer_science/number_type_finder/MainNumberTypeFinder.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#72 Transpose of Matrix
  calculators/src/mathematical/matrix_transpose/MainMatrixTranspose.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#76 functionality to calculate age is added
  calculators/src/health/age_calculator/MainAgeCalculator.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#73 added decimal to binary convertor
  calculators/src/computer_science/DecToBinAndBinToDec/MainDecToBinAndBinToDec.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#79 Added Hexadecimal to Octal and vice versa Calculator
  calculators/src/computer_science/hexToOctAndOctToHex/MainHexToOctAndOctToHex.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#80 Added MainPHCalc.js
  calculators/src/chemistry/phCalc/MainPHCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#83 BMI Calculator
  calculators/src/health/BMI/MainBMI.js
  calculators/src/health/BMI/MainBmi.css
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#84 Fix: #75 Added the Searching Visualizer
  calculators/src/computer_science/searching_visualizer/MainSearchingVisualizer.js
Labels: hard, hacktoberfest2023, hacktoberfest-accepted

#87 Added MainAsciiTextToBinAndBinToAsciiText.js
  calculators/src/computer_science/asciiTextToBinAndBinToAsciiText/MainAsciiTextToBinAndBinToAsciiText.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#94 XOR Calculator
  calculators/src/computer_science/xor_operator/MainXOROperator.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#92 Fix: #89 Added ML performance Evaluation Calculator
  calculators/src/computer_science/mLModelPerformanceEvaluationCalculator/MainMLModelPerformanceEvaluationCalculator.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted, admin-appreciation 🎁

#93 Fd maturity calc
  calculators/src/finance/fd_maturity_calculator/MainFDMaturityCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#103 Added RD Maturity Calculator
  calculators/src/finance/rd_maturity_calculator/MainRDMaturityCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#101 Expense-Tracker
  calculators/src/finance/expense_tracker/Context/context.jsx
  calculators/src/finance/expense_tracker/Context/contextReducer.js
  calculators/src/finance/expense_tracker/MainExpenseTracker.js
  calculators/src/finance/expense_tracker/components/Details/Details.jsx
  calculators/src/finance/expense_tracker/components/Details/styles.js
  calculators/src/finance/expense_tracker/components/Main/Form/Form.jsx
  calculators/src/finance/expense_tracker/components/Main/Form/styles.js
  calculators/src/finance/expense_tracker/components/Main/List/List.jsx
  calculators/src/finance/expense_tracker/components/Main/List/styles.js
  calculators/src/finance/expense_tracker/components/Main/Main.jsx
  calculators/src/finance/expense_tracker/components/Main/styles.js
  calculators/src/finance/expense_tracker/constants/categories.js
  calculators/src/finance/expense_tracker/utils/formatdate.js
Labels: hard, hacktoberfest2023, hacktoberfest-accepted

#95 This calculator group points which are on the same side of the line
  calculators/package-lock.json
  calculators/package.json
  calculators/src/mathematical/pointsOnSameSideOfLineFinder/MainPointsOnSameSideOfLineFinder.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#116 Added AND operator
  calculators/src/computer_science/and_operator/MainANDOperator.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#127 Inverse of a matrix #40
  calculators/package-lock.json
  calculators/package.json
  calculators/src/mathematical/matrix_inverse/MainMatrixInverse.js
  calculators/src/mathematical/matrix_inverse/mainMatrixInverse.css
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#128 Savings Calculator
  calculators/src/finance/savings_calc/MainSavingsCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#129 Graph Maker is created using JS
  calculators/package-lock.json
  calculators/package.json
  calculators/src/mathematical/graph_maker/MainGraphMaker.js
Labels: hard, hacktoberfest2023, hacktoberfest-accepted

#131 Adjoint of a Matrix calculator using ReactJS
  calculators/src/mathematical/matrix_adjoint/MainMatrix.css
  calculators/src/mathematical/matrix_adjoint/MainMatrixAdjoint.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#133 #107 fixed Angle Type Classifier
  calculators/src/mathematical/angleTypeClassifier/MainAngleTypeClassifier.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#134 new calculator first_order_differential_eq_solver added
  calculators/src/mathematical/first_order_differential_eq_solver/MainFirstOrderDifferentialEqSolver.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#137 Implemented Quadratic Equation Intersection Calculator (Fixes #33)
  calculators/src/mathematical/quadratic_eq_intersection/MainQuadraticEquationIntersection.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#138 LCM Calculator Fixed #99
  calculators/src/mathematical/lcmCalc/MainLCMCalc.js
  calculators/src/mathematical/lcmCalc/mainLCMCalc.css
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#139 added NAND operator
  calculators/src/computer_science/nandOperator/MainNANDOperator.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#136 Add: #119 Added the Infix to Postfix and Prefix Calculator
  calculators/src/computer_science/infixToPostAndPreCalc/MainInfixToPostAndPreCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#140 Co-linear Points Finder
  calculators/src/mathematical/coLinearPointsFinder/MainCoLinearPointsFinder.js
Labels: hard, hacktoberfest2023, hacktoberfest-accepted

#141 Update MainMatrixMultiplication.js
  calculators/src/mathematical/matrix_multiplication/MainMatrixMultiplication.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#130 loan repayment calculator
  calculators/src/finance/loan_repayment_calc/MainLoanRepaymentCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#164 Added Coprime Finder
  calculators/src/mathematical/coPrimeFinder/MainCoPrimeFinder.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#166 Molecular weight calc
  calculators/src/chemistry/molecularWeightCalc/MainMolecularWeightCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#173 added NOR operator
  calculators/src/computer_science/and_operator/MainANDOperator.js
  calculators/src/computer_science/nandOperator/MainNANDOperator.js
  calculators/src/computer_science/norOperator/MainNOROperator.js
  calculators/src/computer_science/or_operator/MainOROperator.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#180 Profit Margin Calculator Added
  calculators/src/finance/profitMarginCalc/MainProfitMarginCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#174 Feature/ashishnallana
  calculators/src/mathematical/percentileCalc/MainPercentileCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#184 Simple On-Screen Calculator
  calculators/src/computer_science/simpleOnScreenCalc/MainSimpleOnScreenCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#185 calculate drug dosages based on patient weight and the specific medication requirements.
  calculators/src/health/drugDosageCalc/MainDrugDosageCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#186 APGAR Score Calculator is a tool used to assess the physical conditions of a new born baby immediately after birth.
  calculators/src/health/aPGARScoreCalc/MainAPGARScoreCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#187 Fix: #170 Added IPv4 to IPv6 calculator
  calculators/src/computer_science/iPv4ToiPv6Calc/MainIPv4ToIPv6Calc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#188 Fix: #145 Added Question Paper Builder
  calculators/package-lock.json
  calculators/package.json
  calculators/src/computer_science/questionPaperBuilder/MainQuestionPaperBuilder.js
Labels: hard, hacktoberfest2023, hacktoberfest-accepted

#190 Added color code format converter
  calculators/src/computer_science/colorCodeFormatConverter/MainColorCodeFormatConverter.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#204 Created a distance calculator to calculate distance between 2d and 3d…
  calculators/src/mathematical/distanceFormula/MainDistanceFormula.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#198 Added Triangle Type Finder Calculator
  calculators/src/mathematical/triangleTypeFinder/MainTriangleTypeFinder.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#214 update readme file
  README.md
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#219 added percentage calculator
  calculators/src/mathematical/percentageCalc/MainPercentageCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#206 Added a calculator for calculating the solution of Trignometric Values
  calculators/src/mathematical/trignometricValueCalc/MainTrignometricValueCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#217 Added Profit Loss Calculator
  calculators/src/mathematical/profitLossCalc/MainProfitLossCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#218 created a calculator to find Place and Face Value of digit
  calculators/src/mathematical/placeAndFaceValueCalc/MainPlaceAndFaceValueCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#221 Calculater has been created
  calculators/src/mathematical/factorsOfNumber/MainFactorsOfNumber.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#208 Added code editor for web dev
  calculators/src/computer_science/codeEditorWebDev/MainCodeEditorWebDev.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#223 Number_type_finder
  calculators/src/computer_science/number_type_finder/NumbertypeFinder_2.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#224 Fraction Sorting Calculator
  calculators/src/mathematical/fractionSortingCalculator/MainFractionSortingCalculator.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#228 added equating denominator of fraction
  calculators/src/mathematical/equatingDenominatorOfFraction/MainEquatingDenominatorOfFraction.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#229 Created Fraction to Decimal and vice versa Calc
  calculators/src/computer_science/fracToDecAndDecToFrac/MainFracToDecAndDecToFrac.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#171 Currency conversion
  calculators/package-lock.json
  calculators/package.json
  calculators/src/finance/currency_converter/CurrencyApp.css
  calculators/src/finance/currency_converter/MainCurrencyConverter.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#225 Upgraded Searching Visualizer
  calculators/src/computer_science/searching_visualizer/MainSearchingVisualizer.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#234 Created Table of a number
  calculators/src/mathematical/tableOfNumber/MainTableOfNumber.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#236 Squares and cubes in a range
  calculators/src/mathematical/squareAndCubeCalc/MainSquareAndCubeCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#235 Calculator for checking Points lie inside/outside/on of quadratic curve
  calculators/src/mathematical/pointsInOnOutOfQuadCurveFinder/MainPointsInOnOutOfQuadCurveFinder.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#238 Decimal to 2421 code convertor
  calculators/src/computer_science/dec2421CodeConverter/MainDec2421CodeConverter.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#239 mixed to improper fraction and vice versa
  calculators/src/mathematical/mixedToImproperAndImproperToMixedFraction/MainMixedToImproperAndImproperToMixedFraction.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#242 HCF Calculator
  calculators/src/mathematical/hcfCalc/MainHCFCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#243 added HCF calculator for given set of inputs
  calculators/src/mathematical/hcfCalc/MainHCFCalc.js
Labels: 🎉ranked

#253 it will calculate the area of the 2D shapes
  calculators/src/mathematical/areaOf2DShapes/MainAreaOf2DShapes.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#257 add excess 3 code converter
  calculators/src/computer_science/excess3CodeConverter/MainExcess3CodeConverter.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#227 prefix , postfix to infix calculator
  calculators/src/computer_science/postAndPreToInfixCalc/MainPostAndPreToInfixCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#262 Metric Unit Convertor for Length and Weight
  calculators/src/mathematical/metricUnitConverter/MainMetricUnitConverter.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#259 Converting to Roman Numerals
  calculators/src/mathematical/romanNumeralConverter/MainRomanNumeralConverter.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#261 added calculator to find cube root and square root
  calculators/src/mathematical/cubeRootAndSquareRootCalc/MainCubeRootAndSquareRootCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#263 added an operation on fraction calculator.
  calculators/src/mathematical/operationsOnFractions/MainOperationsOnFractions.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#268 Created factorial calculator
  calculators/src/computer_science/factorialCalc/MainFactorialCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#267 added floating point values in dec to bin calc
  calculators/src/computer_science/DecToBinAndBinToDec/MainDecToBinAndBinToDec.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#270 Add: #151 Added advanced On Screen Calculator
  calculators/package-lock.json
  calculators/package.json
  calculators/src/computer_science/advOnScreenCalc/MainAdvOnScreenCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#289 statistical graph creator
  calculators/package-lock.json
  calculators/package.json
  calculators/src/mathematical/statisticalGraphCreator/MainStatisticalGraphCreator.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#292 Numerals to Words
  calculators/package-lock.json
  calculators/package.json
  calculators/src/mathematical/numeralsToWords/MainNumeralsToWords.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#295 added temperature and time converter
  calculators/src/mathematical/metricUnitConverter/MainMetricUnitConverter.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#301 added Permutation And Combination Calculator
  calculators/src/mathematical/permutationAndCombinationCalc/MainPermutationAndCombinationCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#302 Weight
  calculators/src/physics/cosmoMassConverter/MainCosmoMassConverter.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#306 Added documentation for XOR,NAND & Binary adder
  calculators/src/computer_science/BinaryAdder/InfoBinaryAdder.js
  calculators/src/computer_science/BinaryAdder/MainBinaryAdder.js
  calculators/src/computer_science/nandOperator/InfoNANDOperator.js
  calculators/src/computer_science/nandOperator/MainNANDOperator.js
  calculators/src/computer_science/xor_operator/InfoXOROperator.js
  calculators/src/computer_science/xor_operator/MainXOROperator.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#307 Added documentation for OR Operator and NOR Operator
  calculators/src/computer_science/norOperator/InfoNOROperator.js
  calculators/src/computer_science/norOperator/MainNOROperator.js
  calculators/src/computer_science/or_operator/InfoOROperator.js
  calculators/src/computer_science/or_operator/MainOROperator.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#309 Documentation for LCM,HCF and LogAntilog
  calculators/src/mathematical/hcfCalc/InfoHCFCalc.js
  calculators/src/mathematical/hcfCalc/MainHCFCalc.js
  calculators/src/mathematical/lcmCalc/InfoLCMCalc.js
  calculators/src/mathematical/lcmCalc/MainLCMCalc.js
  calculators/src/mathematical/log_antilog/InfoLogAntilog.js
  calculators/src/mathematical/log_antilog/MainLogAntilog.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#312 Doumented PLaceandFaceValue, PythagorasTheorem, ProfitLoss
  calculators/src/mathematical/placeAndFaceValueCalc/InfoPlaceAndFaceValueCalc.js
  calculators/src/mathematical/placeAndFaceValueCalc/MainPlaceAndFaceValueCalc.js
  calculators/src/mathematical/profitLossCalc/InfoProfitLossCalc.js
  calculators/src/mathematical/profitLossCalc/MainProfitLossCalc.js
  calculators/src/mathematical/pythagorasTheorem/InfoPythagorasTheorem.js
  calculators/src/mathematical/pythagorasTheorem/MainPythagorasTheorem.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#315 Added Random Number Generator
  calculators/src/computer_science/randomNumberGenerator/MainRandomNumberGenerator.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#320 Documentation of Pressure Calculator, pH calculator and Random Number…
  calculators/src/chemistry/phCalc/InfoPHCalc.js
  calculators/src/chemistry/phCalc/MainPHCalc.js
  calculators/src/computer_science/randomNumberGenerator/InfoRandomNumberGenerator.js
  calculators/src/computer_science/randomNumberGenerator/MainRandomNumberGenerator.js
  calculators/src/physics/pressureCalc/InfoPressureCalc.js
  calculators/src/physics/pressureCalc/MainPressureCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#322 added ml data cleaner
  calculators/src/computer_science/dataCleaner/MainDataCleaner.js
Labels: hard, hacktoberfest2023, hacktoberfest-accepted

#310 Added Receipt Generator
  calculators/src/finance/receiptGenerator/MainReceiptGenerator.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#317 added volume of 3D shapes calculator
  calculators/src/mathematical/volume3DShapes/MainVolume3DShapes.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#348 IP Address Numerical Calculator
  calculators/src/computer_science/iPAddressCalc/MainIPAddressCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#349 Added Hamming Code Calculator
  calculators/src/computer_science/hammingCode/MainHammingCode.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#351 Added Amplitude Calculator
  calculators/src/physics/amplitudeCalc/MainAmplitudeCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#364 IEEE754 converter added
  calculators/src/computer_science/iEEE754Converter/MainIEEE754Converter.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#357 Added File-Data Comparator
  calculators/src/computer_science/fileDataComparator/MainFileDataComparator.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#371 [ADDED] : Day Scheduler
  calculators/src/health/dayScheduler/MainDayScheduler.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#369 Density Calculator
  README.md
  calculators/src/physics/densityCalc/InfoDensityCalc.js
  calculators/src/physics/densityCalc/MainDensityCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#367 Novelty Age Calculator
  calculators/src/health/noveltyAgeCalculator/MainNoveltyAgeCalculator.css
  calculators/src/health/noveltyAgeCalculator/MainNoveltyAgeCalculator.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#368 Similarity OF Triangles Calculator
  calculators/src/mathematical/similarityOfTriangleCalc/MainSimilarityOfTriangleCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#269 Number Type Finder
  calculators/src/computer_science/OctToBinAndBinToOct/MainOctToBinAndBinToOct.js
  calculators/src/computer_science/number_type_finder/Amicable.js
  calculators/src/computer_science/number_type_finder/Armstrong.js
  calculators/src/computer_science/number_type_finder/Automorphic.js
  calculators/src/computer_science/number_type_finder/Fibonacci.js
  calculators/src/computer_science/number_type_finder/Happy.js
  calculators/src/computer_science/number_type_finder/Harshad.js
  calculators/src/computer_science/number_type_finder/Kaprekar.js
  calculators/src/computer_science/number_type_finder/MainNumberTypeFinder.js
  calculators/src/computer_science/number_type_finder/NumbertypeFinder_2.js
  calculators/src/computer_science/number_type_finder/Palindromic.js
  calculators/src/computer_science/number_type_finder/Pancake.js
  calculators/src/computer_science/number_type_finder/Perfect.js
  calculators/src/computer_science/number_type_finder/Smith.js
  calculators/src/computer_science/number_type_finder/Taxicab.js
  calculators/src/computer_science/number_type_finder/Zeisel.js
  calculators/src/computer_science/number_type_finder/Zuckerman.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#379 Checksum calculator
  calculators/package-lock.json
  calculators/package.json
  calculators/src/computer_science/checksumCalc/MainChecksumCalc.js
Labels: hard, hacktoberfest2023, hacktoberfest-accepted

#380 Projectile Calculator is created
  calculators/src/physics/projectileCalc/MainProjectileCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#378 IP Address calculator
  calculators/src/computer_science/iPAddressCalc/MainIPAddressCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#388 upgraded oct bin and hex dec calculator
  calculators/src/computer_science/OctToBinAndBinToOct/MainOctToBinAndBinToOct.js
  calculators/src/computer_science/decToHexAndHexToDec/MainDecToHexAndHexToDec.js
  calculators/src/mathematical/areaOf2DShapes/MainAreaOf2DShapes.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#389 upgrading this calculator for new 3D shapes
  calculators/src/mathematical/volume3DShapes/MainVolume3DShapes.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#383 Added latitude, longitude and country for a Satellite's TLE
  calculators/package-lock.json
  calculators/package.json
  calculators/src/space/satelliteLocationUsingTLE/MainSatelliteLocationUsingTLE.js
  calculators/src/space/satelliteLocationUsingTLE/SatellitePosition.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#375 Paragraph summarizer using Reactjs
  calculators/src/computer_science/paraSummarizer/MainParaSummarizer.css
  calculators/src/computer_science/paraSummarizer/MainParaSummarizer.js
  calculators/src/computer_science/paraSummarizer/Summary.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#391 Home Page and Landing page Interface Documentation
  UI_Docs/Calculator Type Interface.pdf
  UI_Docs/Landing page and Home page Interface.pdf
Labels: hard, hacktoberfest2023, hacktoberfest-accepted

#392 Calculator Type Interface documentation
  UI_Docs/Calculator Type Interface.pdf
Labels: hard, hacktoberfest2023, hacktoberfest-accepted

#393 Added Image to Text Reader
  calculators/package-lock.json
  calculators/package.json
  calculators/src/computer_science/imageTextReader/ImageTextReader.js
  calculators/src/computer_science/imageTextReader/MainImageTextReader.js
Labels: hard, hacktoberfest2023, hacktoberfest-accepted

#397 Empirical Formula calculator
  calculators/src/chemistry/empiricalFormulaCalc/MainEmpiricalFormulaCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#399 Differential Calculator
  calculators/src/mathematical/differentialCalc/MainDifferentialCalc.js
Labels: question, hard, hacktoberfest-accepted

#400 Added Base Change Calculator Fixes #374
  calculators/src/computer_science/baseChangeCalculator/MainBaseChangeCalculator.js
Labels: question, medium, hacktoberfest2023

#405 Added Complement Calculator #373
  calculators/src/computer_science/complementCalc/MainComplementCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#370 Added Hamming Distance CAL c
  calculators/src/computer_science/hammingDistance/MainHammingDistance.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#410 updated readme calculators name
  README.md
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#411 Matrix Transpose & Inverse Calculator Documentation
  calculators/src/mathematical/matrix_inverse/InfoMatrixInverse.js
  calculators/src/mathematical/matrix_inverse/MainMatrixInverse.js
  calculators/src/mathematical/matrix_transpose/InfoMatrixTranspose.js
  calculators/src/mathematical/matrix_transpose/MainMatrixTranspose.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#409 Added sumAPGPHP Calculator
  calculators/src/mathematical/sumAPGPHPCalc/MainSumAPGPHPCalc.js
  calculators/src/mathematical/sumAPGPHPCalc/style.css
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#413 Area of 2D Shapes Calculator
  calculators/src/mathematical/areaOf2DShapes/MainAreaOf2DShapes.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#414 added multicurrency change calculator
  calculators/src/finance/multiCurrencyChangeCalc/MainMultiCurrencyChangeCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#420 Transmission Delay Calculator
  calculators/src/computer_science/transmissionDelayCalc/MainTransmissionDelayCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#422 pipes and cisterns calculator
  calculators/src/mathematical/pipesAndCisternsCalc/MainPipesAndCisternsCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#418 POS and SOP converter
  calculators/src/computer_science/pOSSOPConverter/MainPOSSOPConverter.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#421 added multicurrency change calculator
  calculators/src/finance/multiCurrencyChangeCalc/MainMultiCurrencyChangeCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#398 Documentation of Quadratic equation intersaction, polynomial eq…
  calculators/src/mathematical/polyEqRootFinder/InfoPolyEqRootFinder.js
  calculators/src/mathematical/polyEqRootFinder/MainPolyEqRootFinder.js
  calculators/src/mathematical/quadratic_eq_intersection/InfoQuadraticEquationIntersection.js
  calculators/src/mathematical/quadratic_eq_intersection/MainQuadraticEquationIntersection.js
  calculators/src/mathematical/set_operations/InfoSetOperations.js
  calculators/src/mathematical/set_operations/MainSetOperations.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#426 feat: Z-Score Calculator added
  calculators/src/mathematical/zScoreCalc/MainZScoreCalc.css
  calculators/src/mathematical/zScoreCalc/MainZScoreCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#427 Added Surface Area of 3D Shapes
  calculators/src/mathematical/surfaceAreaOf3DShapes/MainSurfaceAreaOf3DShapes.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#430 Created factorial using gamma function calculator
  calculators/src/mathematical/factorialCalc_Gamma/MainFactorialCalc_Gamma.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#429 added kinetic energy calculator
  calculators/src/physics/kineticEnergyCalc/InfoKineticEnergyCalc.js
  calculators/src/physics/kineticEnergyCalc/MainKineticEnergyCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#435 Gray Code Convertor to Binary and Vice Versa
  calculators/src/computer_science/grayCodeCalc/MainGrayCodeCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#431 MUX Caclulator implemented #384
  calculators/package-lock.json
  calculators/package.json
  calculators/src/computer_science/mUXCalc/MainMUXCalc.js
  calculators/src/computer_science/propagationDelayCalc/MainPropagationDelayCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#436 Implemented: Delay Calculator (Calculating Propagation Delay) #396
  calculators/src/computer_science/propagationDelayCalc/MainPropagationDelayCalc.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#440 Added GDP Calculator
  calculators/package-lock.json
  calculators/src/finance/gDPCalc/MainGDPCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#452 add tip calculator
  calculators/src/finance/tipCalc/MainTipCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#450 Added speed and pressure convertor under mathematics category in metric unit convertor folder
  calculators/src/mathematical/metricUnitConverter/MainMetricUnitConverter.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#445 added mandala creator
  calculators/src/art/mandalaCreater/MainMandala.css
  calculators/src/art/mandalaCreater/MainMandalaCreater.js
Labels: hard, hacktoberfest2023, hacktoberfest-accepted, admin-choice

#453 Feat/work calculator
  calculators/src/physics/workCalc/MainWorkCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#444 Added time dilation calculator
  calculators/src/physics/timeDilationCalc/InfoTimeDilationCalc.js
  calculators/src/physics/timeDilationCalc/MainTimeDilationCalc.js
Labels: easy, hacktoberfest2023, hacktoberfest-accepted

#441 Carroll's Cave of Knowledge
  calculators/src/computer_science/carrollsCaveOfKnowledge/MainCarrollsCaveOfKnowledge.js
Labels: medium, hacktoberfest2023, hacktoberfest-accepted

#428 Avatar Creator
  calculators/package-lock.json
  calculators/package.json
  calculators/src/art/avatarCreater/MainAvatarCreater.js
  calculators/src/art/picEditor/MainPicEditor.js
Labels: hard, hacktoberfest2023, hacktoberfest-accepted, admin-choice
